services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce_app
    ports:
      - 5442:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
